Refresh patches.suse/0001-memcg-kmem-further-deprecate-kmem.limit_in_bytes.patch.
Drop memcg_update_kmem_limit() as it is unused now and the compiler
complains:
mm/memcontrol.c:2972:12: error: ‘memcg_update_kmem_limit’ defined but not used

This is done in the upstream patch too.

suse-commit: 660e644b48a82a717eb1715e401c3469a35fc613